### ISSUE TITLE
Openssl error.

### ISSUE THREAD

**Issue by SunPodder** [cyberkallan/inshackle-bot#28]
After following celebgram it shows the following error
`inshackle.sh: line 455: openssl: command not found`

Following is not also increasing. Last time when i used it it worked fine, and i didn't get any error. But this time getting this error and it isn't working.

**Comment by BotKi11eR** [comment]
Brother did you find the fix for this?

**Comment by SunPodder** [comment]
@BotKi11eR Yeah. Actually I was totally new back than😅
You just have to install openssl. Use bellow command
```bash
apt install openssl
```

**Comment by SunPodder** [comment]
Though I have still the 2nd issue. Following doesn't increases. I tried debug the script and found that it is something with the instagram api. They are asking for verification, and after verifying it still throws the verification error.

Thanks for the ping. I was working with a similar script, but I suddenly forgot about that and moved onto new projects. I will give a look on that project again. You can follow me for more updates

**Comment by BotKi11eR** [comment]
I did install the Openssl but yeah the following still not increasing.. I am new just started 1 week ago and trying to learn commands n stuff, but there are a lot of issurs and I can't find a proper place to talk about all issues n stuff, googling doesn't help much in most cases If you know any group/ site where you can talk to others and get fixes kindly let me know . Good luck for your works :)

**Comment by SunPodder** [comment]
Termux commands are pure linux commands. So you can join any linux groups. Reddit is a good place what you are looking for.

**Comment by Hamzasya96** [comment]
Çözüldü mü ben de de aynı sorun var
